##########################
# Versions updated to last on conda-forge and pypi
# Author: Julian Bolivar
# Date: 2023-05-27
# Version: 1.0.0
##########################
name: census_processor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - dvc=2.58.1
  - numpy=1.24.3
  - cookiecutter=2.1.1
  - matplotlib=3.7.1
  - pandas=2.0.1
  - pytest=7.3.1
  - flake8=6.0.0
  - pylint=2.17.4
  - autopep8=2.0.2
  - git=2.40.1
  - pip>=23.1.2
  - scikit-learn=1.2.2
  - requests=2.31.0
  - fastapi=0.95.2
  - uvicorn=0.22.0
  - gunicorn=20.1.0
  - httpx=0.24.1