##########################
# Versions updated to last on conda-forge and pypi
# Author: Julian Bolivar
# Date: 2023-05-15
# Version: 1.1.0
##########################
name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - mlflow
  - numpy
  - ipython
  - notebook
  - jupyterlab
  - seaborn
  - pandas
  - pip=23.1.2
  - ydata-profiling
  - pyarrow
  - pip:
      - wandb==0.15.2
