##########################
# Versions updated to last on conda-forge and pypi
# Author: Julian Bolivar
# Date: 2023-05-27
# Version: 1.0.0
##########################
name: census-eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - numpy=1.23.5
  - jupyterlab=4.0.0
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - pip>=23.1.2
  - ydata-profiling=4.2.0
  - ipywidgets=8.0.6
  - pyarrow=12.0.0
